name: Close Improper Pull Requests
on:
  pull_request_target:
    branches:
      - master

jobs:
  check_valid_head:
    runs-on: ubuntu-latest
    steps:
      - name: Check for valid head
        if: ${{ github.head_ref != 'release' && !contains(github.head_ref, 'hotfix/') }}
        uses: superbrothers/close-pull-request@v3
        with:
          comment: To create a pull request into master, you must use a head of 'release' or 'hotfix/*'.