name: Close Improper Pull Requests
on:
  pull_request_target:
    branches:
      - main

jobs:
  check_pr_head:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        if:  ${{ github.head_ref != 'release' }} && ${{ github.head_ref != 'hotfix/*' }}
        run: echo "invalid PR!"