name: Close Improper Pull Requests
on:
  pull_request:
    branches:
      - main

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check for valid head
        if: ${{ github.head_ref != 'release' }} || ${{ github.head_ref != 'hotfix/*' }}
        run:
          runs-on: ubuntu-latest
          steps:
          - uses: superbrothers/close-pull-request@v3